# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  remix-lib:
    docker:
        - image: circleci/node:7.10
    environment:
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install && npm run bootstrap
      - run: cd remix-lib && npm test
            
  remix-core:
    docker:
        - image: circleci/node:7.10
    environment:
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install && npm run bootstrap
      - run: cd remix-core && npm test
            
  remix-solidity:
    docker:
        - image: circleci/node:7.10
    environment:
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install && npm run bootstrap
      - run: cd remix-solidity && npm test
   
  remix-debug:
     docker:
        - image: circleci/node:7.10
     environment:
     working_directory: ~/repo
     steps:
      - checkout
      - run: npm install && npm run bootstrap
      - run: cd remix-debug && npm test
             
workflows:
  version: 2
  build_all:
    jobs:
      - remix-lib
      - remix-core
      - remix-solidity
      - remix-debug
      
